language: c
sudo: required
os: linux
services:
  - docker
branches:
  only:
    - master

env: MEDUSA_ANSIBLE_IMAGE=amireh/ansible:latest

before_install:
  - curl -sS https://raw.githubusercontent.com/amireh/medusa/master/medusa-installer | bash
  - source ~/.bashrc

install:
  - docker build -t amireh/ansible:latest ansible/
  - docker build -t amireh/kong-dev:latest kong-dev/

script:
  - ( cd ansible && ./test/main.sh )
  - ( cd kong-dev && ./scripts/ci.sh )