language: c
sudo: required
os: linux
services:
  - docker

# skip the install step
# see https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Installation-Step
install: true

before_install:
  - |
    on_change_of() {
      local image="$1"

      shift 1

      if git diff --name-only HEAD~1 | grep -Eq "^$image/"; then
        ( cd "$image" && "$@" )
      fi
    }
  - on_change_of 'ansible' ./travis-ci/before_install.sh
  - on_change_of 'kong-dev' ./travis-ci/before_install.sh

script:
  - /bin/true