language: c
sudo: required
os: linux
services:
  - docker
branches:
  only:
    - master

env: MEDUSA_ANSIBLE_IMAGE=amireh/ansible:latest

before_install:
  - curl -sS https://raw.githubusercontent.com/amireh/medusa/master/medusa-installer | bash
  - source ~/.bashrc

install:
  - docker build -t amireh/ansible:latest ansible/
  - docker build --build-arg KONG_VERSION=0.11.2 -t amireh/kong-dev:0.11.2 kong-dev/
  - docker build --build-arg KONG_VERSION=0.12.3 -t amireh/kong-dev:0.12.3 kong-dev/

script:
  - ( cd ansible && ./test/main.sh )
  - ( cd kong-dev && KONG_VERSION=0.11.2 ./scripts/ci.sh)
  - ( cd kong-dev && KONG_VERSION=0.12.3 ./scripts/ci.sh)