- hosts: localhost
  gather_facts: no
  tasks:
    - name: run tests
      block:
        - name: launch a pg docker container for testing
          docker_container:
            image: postgres:9.5-alpine
            name: kong-dev-test-db
            state: started
            cleanup: yes
            detach: yes
            command: postgres -c "listen_addresses=*"

        - name: launch a kong docker container for testing
          docker_container:
            image: "amireh/kong-dev:{{ version | default('latest') }}"
            name: kong-dev-test
            state: started
            cleanup: yes
            detach: yes
            interactive: yes
            command: sh
            links:
              - kong-dev-test-db
            env:
              KONG_DEV_ROCKS_DIR: /mnt/src/rocks
              KONG_PG_HOST: kong-dev-test-db
              KONG_PG_PORT: 5432
              KONG_PG_USER: postgres
              KONG_PG_DATABASE: kong_test
              KONG_CUSTOM_PLUGINS: 'null'
            volumes:
              - "{{ medusa_host_dir }}:/mnt/src:ro"

        - name: wait for pg to start
          wait_for:
            port: 5432
            host: kong-dev-test-db
          delegate_to: kong-dev-test

        - name: create kong db
          command: createdb -h kong-dev-test-db -U postgres kong_test
          delegate_to: kong-dev-test
          register: createdb_result
          failed_when: "createdb_result.rc != 0 and 'already exists' not in createdb_result.stderr"

        - name: busted-kong works
          command: busted-kong /mnt/src/rocks
          environment:
            KONG_DEV_LUACOV_OUTDIR: /tmp/luacov
          delegate_to: kong-dev-test

        - name: coverage is generated
          command: find /tmp/luacov -type f
          register: coverage_files
          delegate_to: kong-dev-test

        - assert:
            that:
              - "'/tmp/luacov/luacov.stats.out' in coverage_files.stdout"
              - "'/tmp/luacov/index.html' in coverage_files.stdout"

      always:
        - name: remove docker containers
          docker_container:
            name: "{{ item }}"
            state: absent
          with_items:
            - kong-dev-test-db
            - kong-dev-test
