FROM certbot/certbot:v0.25.1

RUN pip install --no-cache-dir \
  certbot-dns-cloudflare \
  certbot-dns-cloudxns \
  certbot-dns-digitalocean \
  certbot-dns-dnsimple \
  certbot-dns-dnsmadeeasy \
  certbot-dns-google \
  certbot-dns-luadns \
  certbot-dns-nsone \
  certbot-dns-rfc2136 \
  certbot-dns-route53
